// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9Kjg-6QOTuQdtleuwSXDU8GkCYS2pCE',
    appId: '1:898243348121:web:852c2cfa6f001177051a08',
    messagingSenderId: '898243348121',
    projectId: 'shopsyra-e618e',
    authDomain: 'shopsyra-e618e.firebaseapp.com',
    storageBucket: 'shopsyra-e618e.firebasestorage.app',
    measurementId: 'G-HW5F20QGV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMmTDwI8HRIuPQmB49e9hIBC43AH2gW0',
    appId: '1:898243348121:android:c6e2545c57517123051a08',
    messagingSenderId: '898243348121',
    projectId: 'shopsyra-e618e',
    storageBucket: 'shopsyra-e618e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVAoDi2uKfhIW4qorcaADOTHCBjwxKiiA',
    appId: '1:898243348121:ios:4684e0442b09d302051a08',
    messagingSenderId: '898243348121',
    projectId: 'shopsyra-e618e',
    storageBucket: 'shopsyra-e618e.firebasestorage.app',
    iosBundleId: 'com.example.shopsyra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVAoDi2uKfhIW4qorcaADOTHCBjwxKiiA',
    appId: '1:898243348121:ios:4684e0442b09d302051a08',
    messagingSenderId: '898243348121',
    projectId: 'shopsyra-e618e',
    storageBucket: 'shopsyra-e618e.firebasestorage.app',
    iosBundleId: 'com.example.shopsyra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc9Kjg-6QOTuQdtleuwSXDU8GkCYS2pCE',
    appId: '1:898243348121:web:a633c54993b44d8a051a08',
    messagingSenderId: '898243348121',
    projectId: 'shopsyra-e618e',
    authDomain: 'shopsyra-e618e.firebaseapp.com',
    storageBucket: 'shopsyra-e618e.firebasestorage.app',
    measurementId: 'G-DPMMZ97WHY',
  );

}